//! Integration tests for the rollback / snapshot engine.
//!
//! These tests exercise the real public API from `iptv_hub_core::rollback`:
//! `create_archive`, `restore_archive`, `sweep_expired`, `begin_swap`,
//! `SwapGuard::commit`, and `recover_orphan_swaps`. Per CONTRACT.md §2.2, no
//! mocks — every test stands up a real on-disk tree under `tempfile::TempDir`,
//! drives the public functions, and asserts byte-level outcomes.

#![allow(
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::uninlined_format_args
)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use iptv_hub_core::paths::AppPaths;
use iptv_hub_core::rollback::{
    begin_swap, create_archive, recover_orphan_swaps, restore_archive, sweep_expired,
};
use sha2::{Digest as _, Sha256};
use tempfile::TempDir;

// ── helpers ──────────────────────────────────────────────────────────────────────

async fn make_paths(root: &Path) -> AppPaths {
    let paths = AppPaths::for_tests(root);
    paths.ensure_exist().await.expect("ensure_exist");
    paths
}

fn sha256_file(path: &Path) -> String {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("read {}: {}", path.display(), e));
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    hex::encode(hasher.finalize())
}

fn write_file(path: &Path, contents: &[u8]) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap_or_else(|e| panic!("mkdir {}: {}", parent.display(), e));
    }
    fs::write(path, contents).unwrap_or_else(|e| panic!("write {}: {}", path.display(), e));
}

// ── tests ────────────────────────────────────────────────────────────────────────

/// Snapshot a tree containing a symlink, restore, and assert the symlink survives.
///
/// On Windows, creating a file symlink without admin/developer-mode privileges
/// fails with `ERROR_PRIVILEGE_NOT_HELD` (1314). In that case we emit a clear
/// skip notice and return successfully — the contract permits skipping with a
/// visible message, not silent disabling.
#[tokio::test]
async fn snapshot_restore_symlinks() {
    let tmp = TempDir::new().expect("tempdir");
    let source_dir = tmp.path().join("source");
    let target_file = source_dir.join("real.txt");
    let link_path = source_dir.join("link.txt");

    fs::create_dir_all(&source_dir).expect("mkdir source");
    fs::write(&target_file, b"hello-from-target").expect("write target");

    #[cfg(unix)]
    {
        std::os::unix::fs::symlink("real.txt", &link_path).expect("symlink");
    }
    #[cfg(windows)]
    {
        if let Err(e) = std::os::windows::fs::symlink_file("real.txt", &link_path) {
            eprintln!(
                "\nsnapshot_restore_symlinks: SKIPPING — cannot create symlink on this Windows host \
                 (need admin or Developer Mode). os error: {}",
                e
            );
            return;
        }
    }

    let cache_root = tmp.path().join("cache");
    fs::create_dir_all(&cache_root).expect("mkdir cache");

    let snap = create_archive("symlink-app", "v1", &source_dir, &cache_root)
        .await
        .expect("create_archive");
    assert!(snap.path.exists(), "archive file should exist");

    // Delete the entire source tree.
    fs::remove_dir_all(&source_dir).expect("remove source");
    assert!(!source_dir.exists());

    restore_archive(&snap.path, &source_dir)
        .await
        .expect("restore_archive");

    // The real file must be back, byte-identical.
    let real_after = fs::read(source_dir.join("real.txt")).expect("read real after restore");
    assert_eq!(real_after, b"hello-from-target");

    // The symlink must be back, pointing at "real.txt".
    let meta = fs::symlink_metadata(&link_path).expect("symlink metadata");
    assert!(
        meta.file_type().is_symlink(),
        "link.txt should be a symlink after restore (was {:?})",
        meta.file_type()
    );
    let resolved = fs::read_link(&link_path).expect("read_link");
    assert_eq!(
        resolved,
        PathBuf::from("real.txt"),
        "symlink target should be preserved"
    );
}

/// Snapshot a 5 MiB binary file with deterministic-but-non-trivial content,
/// restore, and assert byte-for-byte equality via SHA-256.
#[tokio::test]
async fn snapshot_restore_large_binary() {
    let tmp = TempDir::new().expect("tempdir");
    let source_dir = tmp.path().join("source");
    let big_path = source_dir.join("payload.bin");

    fs::create_dir_all(&source_dir).expect("mkdir source");

    // 5 MiB of pseudo-random-looking bytes generated by a tiny LCG. We avoid the
    // `rand` crate because adding a dev-dep is out of scope for this slice.
    let mut buf = vec![0u8; 5 * 1024 * 1024];
    let mut state: u64 = 0x_C0FF_EE12_3456_789A;
    for chunk in buf.chunks_mut(8) {
        state = state
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1);
        let bytes = state.to_le_bytes();
        for (i, b) in chunk.iter_mut().enumerate() {
            *b = bytes[i];
        }
    }
    fs::write(&big_path, &buf).expect("write big file");
    let expected_sha = sha256_file(&big_path);

    let cache_root = tmp.path().join("cache");
    fs::create_dir_all(&cache_root).expect("mkdir cache");
    let snap = create_archive("big-app", "v1", &source_dir, &cache_root)
        .await
        .expect("create_archive");
    assert!(snap.size_bytes > 0);
    // tar.zst of a 5 MiB random blob should be at most ~5.1 MiB; sanity check
    // that compression didn't explode catastrophically.
    assert!(
        snap.size_bytes < 8 * 1024 * 1024,
        "tar.zst of 5MiB random data was {} bytes, suspiciously large",
        snap.size_bytes
    );

    fs::remove_dir_all(&source_dir).expect("remove source");
    restore_archive(&snap.path, &source_dir)
        .await
        .expect("restore_archive");

    let actual_sha = sha256_file(&big_path);
    assert_eq!(
        actual_sha, expected_sha,
        "restored payload must be byte-identical to original"
    );
}

/// Snapshot a tree containing two empty directories, restore, and assert that
/// the empty dirs are recreated. `tar` only preserves empty directories when
/// they are appended explicitly — `create_archive` does so via `WalkDir`.
#[tokio::test]
async fn snapshot_restore_empty_dirs() {
    let tmp = TempDir::new().expect("tempdir");
    let source_dir = tmp.path().join("source");
    let empty1 = source_dir.join("dir").join("empty1");
    let empty2 = source_dir.join("dir").join("empty2");
    let real_file = source_dir.join("dir").join("file.txt");

    fs::create_dir_all(&empty1).expect("mkdir empty1");
    fs::create_dir_all(&empty2).expect("mkdir empty2");
    write_file(&real_file, b"non-empty sibling");

    let cache_root = tmp.path().join("cache");
    fs::create_dir_all(&cache_root).expect("mkdir cache");
    let snap = create_archive("empty-dirs-app", "v1", &source_dir, &cache_root)
        .await
        .expect("create_archive");

    fs::remove_dir_all(&source_dir).expect("remove source");
    restore_archive(&snap.path, &source_dir)
        .await
        .expect("restore_archive");

    assert!(
        empty1.is_dir(),
        "empty1 should exist as a directory after restore"
    );
    assert!(
        empty2.is_dir(),
        "empty2 should exist as a directory after restore"
    );
    assert_eq!(fs::read_dir(&empty1).expect("read empty1").count(), 0);
    assert_eq!(fs::read_dir(&empty2).expect("read empty2").count(), 0);
    assert!(real_file.exists(), "sibling file should also be restored");
}

/// Place three "snapshot" files under `<root>/rollback/<app>/`, age one of them
/// to 8 days ago using `File::set_modified`, run `sweep_expired(7)`, and assert
/// exactly one file was deleted.
#[tokio::test]
async fn expiry_sweep_deletes_old_snapshots() {
    let tmp = TempDir::new().expect("tempdir");
    let rollback_root = tmp.path().join("rollback");
    let app_dir = rollback_root.join("an-app");
    fs::create_dir_all(&app_dir).expect("mkdir app dir");

    let fresh = app_dir.join("fresh.tar.zst");
    let recent = app_dir.join("recent.tar.zst");
    let old = app_dir.join("old.tar.zst");
    for p in [&fresh, &recent, &old] {
        fs::write(p, b"snapshot bytes").unwrap_or_else(|e| panic!("write {}: {}", p.display(), e));
    }

    // Set the "old" file's mtime to 8 days ago.
    let eight_days_ago = SystemTime::now()
        .checked_sub(Duration::from_secs(8 * 86_400))
        .expect("now - 8d");
    {
        let f = fs::OpenOptions::new()
            .write(true)
            .open(&old)
            .expect("open old");
        f.set_modified(eight_days_ago).expect("set_modified on old");
    }

    let deleted = sweep_expired(&rollback_root, 7)
        .await
        .expect("sweep_expired");
    assert_eq!(deleted, 1, "exactly one snapshot should be expired");
    assert!(!old.exists(), "old.tar.zst should have been deleted");
    assert!(fresh.exists(), "fresh.tar.zst must still exist");
    assert!(recent.exists(), "recent.tar.zst must still exist");
}

/// Sweep against a nonexistent root must be a no-op success.
#[tokio::test]
async fn expiry_sweep_handles_missing_root() {
    let tmp = TempDir::new().expect("tempdir");
    let nonexistent = tmp.path().join("does-not-exist");
    let deleted = sweep_expired(&nonexistent, 7).await.expect("sweep_expired");
    assert_eq!(deleted, 0);
}

/// `begin_swap` writes a marker. After `commit()` the marker file must be gone.
#[tokio::test]
async fn swap_guard_commit_removes_marker() {
    let tmp = TempDir::new().expect("tempdir");
    let paths = make_paths(tmp.path()).await;

    // The "snapshot" and "target" don't matter for this test — commit doesn't
    // touch them. But provide real paths so the marker JSON is valid.
    let snapshot = tmp.path().join("apps").join("cache").join("dummy.tar.zst");
    fs::write(&snapshot, b"not used in this test").expect("write dummy");
    let target = tmp
        .path()
        .join("apps")
        .join("upstream")
        .join("dummy-target");

    let guard = begin_swap("commit-test", &paths, &snapshot, &target).expect("begin_swap");
    let marker_path = guard.marker_path().to_path_buf();
    assert!(
        marker_path.exists(),
        "marker should be on disk after begin_swap"
    );

    guard.commit().expect("commit");
    assert!(
        !marker_path.exists(),
        "marker file should be removed by commit()"
    );
}

/// Drop a `SwapGuard` without committing, then call `recover_orphan_swaps`. It
/// must find the orphan marker, restore from the recorded snapshot, and remove
/// the marker.
#[tokio::test]
async fn crash_recovery_restores_when_marker_present() {
    let tmp = TempDir::new().expect("tempdir");
    let paths = make_paths(tmp.path()).await;

    // Build a real "before" tree, snapshot it, then mutate the tree to simulate
    // a half-finished swap that was killed mid-way.
    let install_dir = tmp.path().join("apps").join("upstream").join("an-app");
    fs::create_dir_all(&install_dir).expect("mkdir install");
    fs::write(install_dir.join("hello.txt"), b"BEFORE").expect("write before");

    let cache_root = tmp.path().join("apps").join("cache");
    let snap = create_archive("recover-app", "v1", &install_dir, &cache_root)
        .await
        .expect("create_archive");

    // Begin the swap, then "crash" by overwriting the target with bogus content
    // and dropping the guard without commit().
    {
        let _guard =
            begin_swap("recover-app", &paths, &snap.path, &install_dir).expect("begin_swap");
        fs::write(install_dir.join("hello.txt"), b"AFTER-but-crashed").expect("write after");
        // Add a stray file that should disappear after recovery.
        fs::write(install_dir.join("partial-extract.tmp"), b"junk").expect("write junk");
        // Guard drops here without commit — marker stays on disk.
    }

    let marker_path = paths
        .apps_root()
        .join("cache")
        .join("rollback")
        .join("recover-app.swap.marker");
    assert!(marker_path.exists(), "marker should be left on disk");

    let recovered = recover_orphan_swaps(&paths)
        .await
        .expect("recover_orphan_swaps");
    assert_eq!(recovered, vec!["recover-app".to_string()]);

    // Restored content must be the BEFORE content.
    let restored = fs::read(install_dir.join("hello.txt")).expect("read restored");
    assert_eq!(
        restored, b"BEFORE",
        "rollback should restore original content"
    );
    // Stray file from the half-finished swap must be gone — `restore_archive`
    // wipes the target before extracting.
    assert!(
        !install_dir.join("partial-extract.tmp").exists(),
        "stray half-extracted file must be cleared by restore"
    );
    // Marker must be removed by recovery.
    assert!(
        !marker_path.exists(),
        "marker should be removed after successful recovery"
    );
}

/// `recover_orphan_swaps` against an empty rollback dir is a no-op.
#[tokio::test]
async fn recovery_with_no_markers_is_noop() {
    let tmp = TempDir::new().expect("tempdir");
    let paths = make_paths(tmp.path()).await;

    let recovered = recover_orphan_swaps(&paths)
        .await
        .expect("recover_orphan_swaps");
    assert!(
        recovered.is_empty(),
        "no markers → empty recovery list, got {:?}",
        recovered
    );
}

/// A corrupt marker is quarantined (renamed to `*.corrupt`) rather than
/// deleted; the recovery function must not panic.
#[tokio::test]
async fn corrupt_marker_is_quarantined() {
    let tmp = TempDir::new().expect("tempdir");
    let paths = make_paths(tmp.path()).await;

    let rollback_dir = paths.apps_root().join("cache").join("rollback");
    fs::create_dir_all(&rollback_dir).expect("mkdir rollback");
    let corrupt_marker = rollback_dir.join("corrupt-app.swap.marker");
    fs::write(&corrupt_marker, b"{ this is not valid json").expect("write corrupt marker");

    let recovered = recover_orphan_swaps(&paths)
        .await
        .expect("recover_orphan_swaps");
    assert!(
        recovered.is_empty(),
        "corrupt marker should not appear in recovered list"
    );
    assert!(
        !corrupt_marker.exists(),
        "original corrupt marker should be renamed"
    );
    let quarantine = rollback_dir.join("corrupt-app.swap.marker.corrupt");
    assert!(
        quarantine.exists(),
        "quarantined marker should exist at {}",
        quarantine.display()
    );
}
