"""Merge per-app docker-compose service fragments into one valid YAML.

Reads every YAML file passed on the command line, merges by union under each
standard compose top-level key (`services`, `volumes`, `networks`, `configs`,
`secrets`), fails loudly on duplicate service / volume names, and emits the
merged document on stdout.

Usage:
    python _merge_compose_fragments.py FRAG1 [FRAG2 ...] > merged.yml

Exit codes:
    0   merged successfully
    1   YAML parse failure or duplicate key collision
    2   no fragment paths supplied
"""
from __future__ import annotations

import io
import sys
from pathlib import Path

import yaml

# Force UTF-8 stdout. Python on Windows defaults to cp1252, which corrupts any
# non-ASCII bytes (em-dashes, etc.) emitted by yaml.safe_dump or our own header.
# The reconfigure path is preferred (Python 3.7+); the TextIOWrapper fallback
# is for older interpreters / unusual stdouts.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")
else:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", newline="\n")

TOP_LEVEL_KEYS = {"services", "volumes", "networks", "configs", "secrets"}


def merge(out: dict, frag: dict, source: str) -> None:
    """Merge `frag` into `out`. Fail on duplicate service/volume names."""
    for key, val in frag.items():
        if key not in TOP_LEVEL_KEYS:
            print(
                f"_merge_compose_fragments: WARN unknown top-level key '{key}' in {source} — preserving",
                file=sys.stderr,
            )
            out.setdefault("_extra", {}).setdefault(source, {})[key] = val
            continue
        if not isinstance(val, dict):
            print(
                f"_merge_compose_fragments: top-level '{key}' in {source} is not a mapping; skipping",
                file=sys.stderr,
            )
            continue
        bucket = out.setdefault(key, {})
        for sub_name, sub_val in val.items():
            if sub_name in bucket:
                print(
                    f"_merge_compose_fragments: ERROR duplicate {key}.{sub_name} (first seen earlier, again in {source})",
                    file=sys.stderr,
                )
                sys.exit(1)
            bucket[sub_name] = sub_val


def main() -> int:
    paths = sys.argv[1:]
    if not paths:
        print("usage: _merge_compose_fragments.py FRAG1 [FRAG2 ...]", file=sys.stderr)
        return 2

    out: dict = {}
    for p in paths:
        text = Path(p).read_text(encoding="utf-8")
        try:
            doc = yaml.safe_load(text)
        except yaml.YAMLError as exc:
            print(f"_merge_compose_fragments: YAML parse failed for {p}: {exc}", file=sys.stderr)
            return 1
        if doc is None:
            continue
        if not isinstance(doc, dict):
            print(f"_merge_compose_fragments: {p} top-level is not a mapping; skipping", file=sys.stderr)
            continue
        merge(out, doc, p)

    if "_extra" in out:
        # Don't pollute the compose output with our diagnostic bucket; just drop it.
        del out["_extra"]

    if not out:
        # No fragments contributed anything — emit a no-op placeholder so
        # `docker compose -f docker-compose.yml -f docker-compose.apps.yml`
        # still parses.
        out = {
            "services": {
                "_placeholder_unused": {
                    "image": "busybox:1.36",
                    "command": ["sh", "-c", "sleep infinity"],
                    "profiles": ["never"],
                }
            }
        }

    header = (
        "# Generated by deploy/scripts/generate-stack.sh + _merge_compose_fragments.py.\n"
        "# Do not edit by hand — re-run the generator after changing any fragment.\n"
    )
    sys.stdout.write(header)
    yaml.safe_dump(out, sys.stdout, default_flow_style=False, sort_keys=False, width=120)
    return 0


if __name__ == "__main__":
    sys.exit(main())
